# Generated by Django 2.0.4 on 2018-04-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(upload_to='')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
