# Generated by Django 2.0.4 on 2018-04-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='movie_id',
        ),
    ]
