# Generated by Django 2.0.4 on 2018-04-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180422_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.SlugField(blank=True),
        ),
    ]
