# Generated by Django 2.0.4 on 2018-04-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('user', '0004_auto_20180413_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityType', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='followed_by', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='follows', to='user.Profile'),
        ),
        migrations.CreateModel(
            name='AddMovieActivity',
            fields=[
                ('abstractactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.AbstractActivity')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie')),
            ],
            bases=('user.abstractactivity',),
        ),
        migrations.CreateModel(
            name='AddUserActivity',
            fields=[
                ('abstractactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.AbstractActivity')),
            ],
            bases=('user.abstractactivity',),
        ),
        migrations.AddField(
            model_name='profile',
            name='activities',
            field=models.ManyToManyField(related_name='activities', to='user.AbstractActivity'),
        ),
        migrations.AddField(
            model_name='adduseractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
