# Generated by Django 2.0.4 on 2018-04-15 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180415_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activities',
        ),
        migrations.AddField(
            model_name='abstractactivity',
            name='activity_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='addmovieactivity',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='main.Movie'),
        ),
        migrations.AlterField(
            model_name='adduseractivity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to='user.Profile'),
        ),
    ]
