# Generated by Django 2.0.4 on 2018-04-16 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180416_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='followrelation',
            name='followed_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='followrelation',
            name='main_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to='user.Profile'),
        ),
    ]
