# Generated by Django 2.0.4 on 2018-04-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20180416_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowRelation',
            new_name='Follow',
        ),
    ]
