# Generated by Django 2.0.4 on 2018-04-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20180416_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='main_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
