# Generated by Django 2.0.4 on 2018-04-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20180416_2337'),
        ('user', '0002_remove_profile_birth_date'),
    ]

    operations = [
    ]
