# Generated by Django 2.0.4 on 2018-04-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20180417_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractactivity',
            name='activity_user',
        ),
        migrations.AddField(
            model_name='abstractactivity',
            name='main_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to='user.Profile'),
        ),
    ]
