# Generated by Django 2.0.4 on 2018-04-17 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20180417_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='main.Movie'),
        ),
    ]
