# Generated by Django 2.0.4 on 2018-04-17 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('user', '0023_auto_20180417_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_user',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='main_user',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.CreateModel(
            name='AddMovieActivity',
            fields=[
                ('abstractactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.AbstractActivity')),
                ('movie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='main.Movie')),
            ],
            bases=('user.abstractactivity',),
        ),
        migrations.CreateModel(
            name='AddUserActivity',
            fields=[
                ('abstractactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.AbstractActivity')),
                ('activity_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to='user.Profile')),
            ],
            bases=('user.abstractactivity',),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='abstractactivity',
            name='main_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to='user.Profile'),
        ),
    ]
